version: 1
formatters:
  simple:
    format: '%(asctime)s :  %(pathname)100s: %(levelname)8s: %(funcName)35s(): %(lineno)4d:     %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: app/logs/logs.log
    level: DEBUG
    maxBytes: 4294967296
    backupCount: 3
loggers:
  logger:
    level: DEBUG
    handlers: [file, console]
    propagate: no

#    DB Log handler added in __init__.py to make file handler able to start work before psqldb works