version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s :  %(filename)30s: %(levelname)8s: %(funcName)35s(): %(lineno)4d:     %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/logs.log
    level: DEBUG
    maxBytes: 4294967296
    backupCount: 3
loggers:
  logger:
    level: DEBUG
    handlers: [file, console]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]
#    DB Log handler added in __init__.py to make file handler able to start work before psqldb works